# Generated by Django 5.1.15 on 2026-04-19 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vm_id", models.CharField(max_length=128, unique=True)),
                ("side", models.CharField(default="radiant", max_length=16)),
                ("hwnds_json", models.JSONField(blank=True, default=list)),
                ("roles_json", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "planner_vm",
            },
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vm_id", models.CharField(db_index=True, max_length=128)),
                ("hwnd", models.BigIntegerField(db_index=True)),
                ("image", models.ImageField(upload_to="planner_frames/%Y/%m/%d/")),
                ("ts_client", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "planner_frame",
                "indexes": [
                    models.Index(
                        fields=["vm_id", "hwnd", "created_at"],
                        name="planner_fra_vm_id_500af4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vm_id", models.CharField(db_index=True, max_length=128)),
                ("hwnd", models.BigIntegerField(db_index=True)),
                ("type", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("done", "done"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("result", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="scripts_host_django.frame",
                    ),
                ),
            ],
            options={
                "db_table": "planner_command",
                "indexes": [
                    models.Index(
                        fields=["vm_id", "hwnd", "status", "created_at"],
                        name="planner_com_vm_id_bfdd41_idx",
                    ),
                    models.Index(
                        fields=["frame", "status", "created_at"],
                        name="planner_com_frame_i_5de85b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActiveFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vm_id", models.CharField(db_index=True, max_length=128)),
                ("hwnd", models.BigIntegerField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "frame",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_link",
                        to="scripts_host_django.frame",
                    ),
                ),
            ],
            options={
                "db_table": "planner_active_frame",
                "indexes": [
                    models.Index(
                        fields=["vm_id", "hwnd"], name="planner_act_vm_id_020907_idx"
                    )
                ],
                "unique_together": {("vm_id", "hwnd")},
            },
        ),
    ]
